name: Java CI with Gradle

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: gradle

      - name: Build with Gradle
        env:
          DB_USERNAME: test
          DB_PASSWORD: test
          CLIENT_ID: fake-id
          CLIENT_SECRET: fake-secret
          EMAIL_USERNAME: fake@mail.com
          EMAIL_PASSWORD: fake-password
          JWT_AT_SECRET: V2VyeWRvbmdTZWNyZXRLZXlGb3JBY2Nlc3NUb2tlbjMyQnl0ZXN0cm9uZw==
          JWT_RT_SECRET: V2VyeWRvbmdTZWNyZXRLZXlGb3JSZWZyZXNoVG9rZW4zMkJ5dGVzdHJvbmc=
        run: chmod +x gradlew && ./gradlew build
